name: CI

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore ./FruitsCatalogAPI.sln

      - name: Build
        run: dotnet build --no-restore ./FruitsCatalogAPI.sln

      - name: Save build output
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            src/API/bin
            src/BusinessLogic/bin
            src/DataAccess/bin
            src/Entities/bin

  unit_tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Restore build output
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Run DataAccess unit tests
        run: dotnet test --no-build --verbosity normal ./tests/DataAccess.UnitTests/DataAccess.UnitTests.csproj

      - name: Run BusinessLogic unit tests
        run: dotnet test --no-build --verbosity normal ./tests/BusinessLogic.UnitTests/BusinessLogic.UnitTests.csproj

  integration_tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"

      - name: Run BusinessLogic integration tests
        run: dotnet test --no-build --verbosity normal ./tests/BusinessLogic.IntegrationTests/BusinessLogic.IntegrationTests.csproj
